### ISSUE TITLE
Build with maven is failing

### ISSUE THREAD

**Issue by aitoroses** [bonitasoft/bonita-ui-designer#11]
Current build is failing with my Mac 10.11.3 (15D21). It's also failing using a docker container running the official maven image [maven:3.2-jdk-7](https://hub.docker.com/_/maven/).

In docker running ubuntu 14.04 it fails during `npm install`.
In the case of my laptop it fails during e2e testing with PhantomJS.

As a workaround I omitted e2e testing during Gulpfile default task with my laptop and works fine.

Please fix this issue!

**Comment by sirnornur** [comment]
Dear developers,
Its impossible to build the module as it is, because, as aitoroses noted above, tests area failing. Please consider fixing this or put some light on this problem, maybe we can fix it. 

In case someone else encounters this problem, as a temporary workaround you can disable the tests:
commenting out the test task on line 124 of the file /frontend/gulpfile.js as following:
` gulp.start([/*'test', */'build']);`

**Comment by cpuy** [comment]
Hi there,

For practical purpose, we are using a private repository to develop and push code to the community repo periodically.

Our push system was broken for a while. We apologize for that and everything should be fine now.

I'll close this issue, please let us know if you get any trouble.

Thx.
Colin
